import { expect, test } from '@playwright/test';
import { collectErrors, demoAction, expectNoErrors, fresh, secondTab, setPersona, setSaveOutcome } from './helpers';

const V = 'strata';

test.describe('Strata', () => {
  test('a draft is a provisional next revision on the axis; commit makes it real', async ({ page }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/contact/lina`);
    await expect(page.getByTestId('rev-7')).toBeVisible();
    await expect(page.getByTestId('tick-draft')).toHaveCount(0);
    const office = page.getByTestId('row-phone#2');
    await office.hover();
    await office.getByTestId('row-edit').click();
    await expect(page.getByTestId('phone-interpretation')).toContainText('+525551234567');
    await page.getByTestId('child-extension').fill('25');
    await page.getByTestId('child-label').fill('Oficina');
    await page.screenshot({ path: `evidence/${V}-contact-light.png` });
    await page.getByTestId('child-submit').click();
    await expect(page.getByTestId('pending-tray')).toContainText('Draft r8');
    await expect(page.getByTestId('tick-draft')).toBeVisible();
    // Validation on a new email.
    await page.getByTestId('add-email').click();
    await page.getByTestId('email-value').fill('nope');
    await page.getByTestId('child-submit').click();
    await expect(page.getByText('This does not look like an email address.')).toBeVisible();
    await page.getByTestId('child-cancel').click();
    const work = page.getByTestId('row-email#1');
    await work.hover();
    await work.getByTestId('row-primary').click();
    await expect(page.getByTestId('pending-list').locator('li')).toHaveCount(2);
    // Preview the draft as Then/Now before committing.
    await page.getByTestId('preview-draft').click();
    await expect(page.getByTestId('draft-banner')).toContainText('Draft r8');
    await expect(page.getByTestId('then-now')).toContainText('r8 draft');
    await expect(page.getByTestId('then-now')).toContainText('ext. 25');
    await page.getByTestId('save').click();
    await expect(page.getByTestId('saved-banner')).toContainText('r8');
    await expect(page.getByTestId('rev-8')).toBeVisible();
    await expect(page.getByTestId('tick-draft')).toHaveCount(0);
    await page.getByTestId('view-evidence').click();
    await expect(page.getByTestId('then-now')).toContainText('r8');
    await page.getByTestId('mode-during').click();
    await expect(page.getByTestId('actions-list').locator('.step')).toHaveCount(2);
    await page.getByTestId('mode-at').click();
    await expect(page.getByTestId('row-phone#2')).toContainText('ext. 25');
    await expect(page.getByTestId('row-email#1')).toContainText('Primary');
    await expectNoErrors(errors);
  });

  test('combined name + phone + address edit is one committed revision; shared address untouched', async ({ page }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/contact/lina`);
    await page.getByTestId('edit-profile').click();
    await page.getByTestId('profile-alias').fill('Lina T.');
    await page.getByTestId('profile-submit').click();
    const mobile = page.getByTestId('row-phone#1');
    await mobile.hover(); await mobile.getByTestId('row-edit').click();
    await page.getByTestId('child-label').fill('Celular');
    await page.getByTestId('child-submit').click();
    const addr = page.getByTestId('row-address#1');
    await addr.hover(); await addr.getByTestId('row-edit').click();
    await page.getByTestId('address-zipCode').fill('62020');
    await page.getByTestId('child-submit').click();
    await expect(page.getByTestId('pending-list').locator('li')).toHaveCount(3);
    await page.keyboard.press('Control+s');
    await expect(page.getByTestId('saved-banner')).toContainText('r8');
    await expect(page.getByTestId('row-address#1')).toContainText('62020');
    await page.goto(`/#/${V}/contact/norte-taller`);
    await expect(page.getByTestId('row-address#1')).toContainText('62000');
    await expectNoErrors(errors);
  });

  test('history: At, Between and During are three shapes on one axis', async ({ page }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/history/lina?rev=4&compare=3&mode=between`);
    await expect(page.getByTestId('historical-banner')).toContainText('r4');
    await expect(page.getByTestId('then-now')).toContainText('62000');
    await expect(page.getByTestId('then-now')).toContainText('62010');
    await page.getByTestId('mode-during').click();
    await expect(page.getByTestId('actions-list').locator('.step')).toHaveCount(3);
    await page.getByTestId('mode-at').click();
    await expect(page.getByTestId('profile-block')).toContainText('Aguilar');
    await expect(page.getByTestId('row-edit')).toHaveCount(0);
    await page.getByTestId('rev-5').click();
    await page.getByTestId('mode-between').click();
    await expect(page.getByTestId('diff-empty')).toContainText('No net difference');
    await page.getByTestId('mode-during').click();
    await expect(page.getByTestId('actions-list').locator('.step')).toHaveCount(2);
    await page.getByTestId('rev-1').click();
    await page.getByTestId('mode-at').click();
    await expect(page.getByTestId('row-phone#1')).toContainText('+52 777 312 3465');
    await page.getByTestId('axis').focus();
    await page.keyboard.press('ArrowRight');
    await expect(page.getByTestId('historical-banner')).toContainText('r2');
    await page.getByTestId('rev-7').click();
    await page.getByTestId('mode-between').click();
    await page.getByTestId('compare-select').selectOption('3');
    await expect(page.getByTestId('then-now')).toContainText('Office');
    await page.screenshot({ path: `evidence/${V}-history-light.png` });
    await demoAction(page, 'history-unavailable');
    await page.getByTestId('rev-1').click();
    await expect(page.getByText('Historical coverage unavailable').first()).toBeVisible();
    await page.getByTestId('back-to-current').click();
    await expect(page.getByTestId('historical-banner')).toHaveCount(0);
    await expectNoErrors(errors);
  });

  test('activity swimlanes: permission, filters, unit panel, axis round trip', async ({ page }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/activity`);
    await expect(page.getByTestId('activity-denied')).toBeVisible();
    await setPersona(page, 'rocio');
    await expect(page.getByTestId('swimlanes')).toBeVisible();
    expect(await page.getByTestId('lane-mark').count()).toBeGreaterThanOrEqual(14);
    await expect(page.getByTestId('lane-mark-op')).toHaveCount(1);
    await page.getByTestId('filter-actor').selectOption('bruno');
    await page.getByTestId('filter-family').selectOption('phone');
    await expect(page.getByTestId('activity-row')).toHaveCount(3);
    await page.getByTestId('filter-q').fill('postal');
    await expect(page.getByTestId('activity-row')).toHaveCount(1);
    await page.getByTestId('activity-row').first().click();
    await expect(page.getByTestId('unit-drawer')).toContainText('Bruno Salas');
    await page.screenshot({ path: `evidence/${V}-activity-light.png` });
    await page.getByTestId('open-contact-revision').click();
    await expect(page.getByTestId('historical-banner')).toContainText('r4');
    await expect(page.getByTestId('then-now')).toBeVisible();
    await page.getByTestId('back-to-activity').click();
    await expect(page).toHaveURL(/actor=bruno/);
    await expect(page.getByTestId('unit-drawer')).toBeVisible();
    await page.getByTestId('filter-q').fill('zzz');
    await expect(page.getByText('No activity matches these filters.')).toBeVisible();
    await expectNoErrors(errors);
  });

  test('lens: references move the axis; proposals become the draft', async ({ page }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/contact/lina`);
    await page.getByTestId('toggle-sidekick').click();
    await page.getByTestId('sidekick-input').fill("What changed in Lina's contact this week?");
    await page.getByTestId('sidekick-send').click();
    const reply = page.getByTestId('sidekick-sidekick').last();
    await expect(reply).toContainText('Revision 4');
    await reply.getByTestId('sidekick-ref').first().click();
    await expect(page.getByTestId('historical-banner')).toContainText('r4');
    await expect(page.getByTestId('then-now')).toContainText('Postal code'.length ? '62010' : '');
    await page.getByTestId('sidekick-input').fill("Show Bruno's phone changes");
    await page.getByTestId('sidekick-send').click();
    await expect(page.getByTestId('sidekick-sidekick').last()).toContainText('cannot open tenant-wide activity');
    await setPersona(page, 'rocio');
    await page.getByTestId('sidekick-input').fill("Show Bruno's phone changes");
    await page.getByTestId('sidekick-send').click();
    await expect(page).toHaveURL(/activity\?.*actor=bruno/);
    await expect(page.getByTestId('activity-row')).toHaveCount(3);
    await setPersona(page, 'mariana');
    await page.goto(`/#/${V}/contact/lina`);
    await page.getByTestId('sidekick-input').fill('Change this extension to 25 and make the work email primary');
    await page.getByTestId('sidekick-send').click();
    const proposal = page.getByTestId('sidekick-proposal').last();
    await expect(proposal).toContainText('extension 12 → 25');
    await proposal.getByTestId('proposal-stage').click();
    await expect(page.getByTestId('tick-draft')).toBeVisible();
    await expect(page.getByTestId('pending-list').locator('li')).toHaveCount(2);
    await page.getByTestId('discard-all').click();
    await expect(page.getByTestId('tick-draft')).toHaveCount(0);
    await page.getByTestId('sidekick-input').fill('change the office extension to 25 and make the work email primary');
    await page.getByTestId('sidekick-send').click();
    await page.getByTestId('sidekick-proposal').last().getByTestId('proposal-save').click();
    await expect(page.getByTestId('saved-banner')).toContainText('r8');
    await expect(page.getByTestId('row-phone#2')).toContainText('ext. 25');
    await page.getByTestId('sidekick-input').fill('What is the primary email?');
    await page.getByTestId('sidekick-send').click();
    await expect(page.getByTestId('sidekick-sidekick').last()).toContainText('lina.torres@vertice-demo.mx');
    await setPersona(page, 'tomas');
    await page.getByTestId('sidekick-input').fill('change the office extension to 30');
    await page.getByTestId('sidekick-send').click();
    await expect(page.getByTestId('sidekick-sidekick').last()).toContainText('no edit grant');
    await expectNoErrors(errors);
  });

  test('two tabs: a revision arrives under the draft; reconcile before committing', async ({ page, context }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/contact/lina`);
    const office = page.getByTestId('row-phone#2');
    await office.hover(); await office.getByTestId('row-edit').click();
    await page.getByTestId('child-extension').fill('25');
    await page.getByTestId('child-submit').click();
    await expect(page.getByTestId('tick-draft')).toBeVisible();
    const bruno = await secondTab(context, `#/${V}/contact/lina`, 'bruno');
    await expect(bruno.getByTestId('presence')).toContainText('Mariana is editing');
    const bOffice = bruno.getByTestId('row-phone#2');
    await bOffice.hover(); await bOffice.getByTestId('row-edit').click();
    await bruno.getByTestId('child-label').fill('Oficina');
    await bruno.getByTestId('child-submit').click();
    await bruno.getByTestId('save').click();
    await expect(bruno.getByTestId('saved-banner')).toContainText('r8');
    await expect(page.getByTestId('stale-banner')).toContainText('r8 arrived');
    await expect(page.getByTestId('rev-8')).toBeVisible();
    await expect(page.getByTestId('tick-draft')).toBeVisible(); // draft preserved
    await expect(page.getByTestId('save')).toBeDisabled();
    await page.getByTestId('review-conflict').click();
    await expect(page.getByTestId('reconcile-item-merged')).toBeVisible();
    await page.screenshot({ path: `evidence/${V}-conflict-light.png` });
    await page.getByTestId('reconcile-save').click();
    await expect(page.getByTestId('saved-banner')).toContainText('r9');
    await expect(page.getByTestId('row-phone#2')).toContainText('Oficina');
    await expect(page.getByTestId('row-phone#2')).toContainText('ext. 25');
    await office.hover(); await office.getByTestId('row-edit').click();
    await page.getByTestId('child-extension').fill('40');
    await page.getByTestId('child-submit').click();
    await demoAction(bruno, 'simulate-bruno-extension');
    await expect(page.getByTestId('stale-banner')).toBeVisible();
    await page.getByTestId('review-conflict').click();
    await expect(page.getByTestId('reconcile-item-conflict')).toBeVisible();
    await page.getByTestId('resolve-mine').check();
    await page.getByTestId('reconcile-save').click();
    await expect(page.getByTestId('saved-banner')).toContainText('r11');
    await bruno.close();
    await expectNoErrors(errors);
  });

  test('personas, uncertain outcome, theme persistence, reset, narrow', async ({ page }) => {
    const errors = collectErrors(page);
    await fresh(page, `#/${V}/contact/lina`);
    await setPersona(page, 'tomas');
    await expect(page.getByTestId('row-edit')).toHaveCount(0);
    await expect(page.getByTestId('rev-7')).toBeVisible();
    await setPersona(page, 'paola');
    await expect(page.getByTestId('directory-banner')).toBeVisible();
    await expect(page.getByTestId('record-directory')).not.toContainText('correo-personal');
    await setPersona(page, 'mariana');
    await setSaveOutcome(page, 'uncertain-committed');
    const mobile = page.getByTestId('row-phone#1');
    await mobile.hover(); await mobile.getByTestId('row-edit').click();
    await page.getByTestId('child-label').fill('Celular');
    await page.getByTestId('child-submit').click();
    await page.getByTestId('save').click();
    await expect(page.getByTestId('uncertain-outcome')).toBeVisible();
    await page.getByTestId('uncertain-check').click();
    await expect(page.getByTestId('uncertain-result')).toContainText('Committed');
    await page.getByRole('button', { name: 'Discard draft' }).click();
    await expect(page.getByTestId('rev-8')).toBeVisible();
    await page.getByTestId('theme-toggle').first().click();
    await page.goto(`/#/${V}/history/lina?rev=4&compare=3&mode=between`);
    await page.reload();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await expect(page.getByTestId('then-now')).toBeVisible();
    await page.getByTestId('toggle-sidekick').click();
    await page.getByTestId('sidekick-input').fill('Who changed the postal code?');
    await page.getByTestId('sidekick-send').click();
    await expect(page.getByTestId('sidekick-sidekick').last()).toContainText('Bruno');
    await page.screenshot({ path: `evidence/${V}-dark.png` });
    await page.getByTestId('theme-toggle').first().click();
    await page.getByRole('button', { name: 'Close lens' }).click();
    await page.goto(`/#/${V}/contact/lina`);
    await demoAction(page, 'demo-reset');
    await expect(page.getByTestId('rev-7')).toBeVisible();
    await expect(page.getByTestId('rev-8')).toHaveCount(0);

    await page.setViewportSize({ width: 414, height: 860 });
    await page.goto(`/#/${V}/contact/lina`);
    await expect(page.getByTestId('section-phone')).toBeVisible();
    const office = page.getByTestId('row-phone#2');
    await office.getByTestId('row-edit').click();
    await expect(page.getByTestId('child-extension')).toBeVisible();
    await page.screenshot({ path: `evidence/${V}-narrow.png` });
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    expect(scrollWidth).toBeLessThanOrEqual(414);
    await expectNoErrors(errors);
  });
});
