<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Framework/Sistrategia.Data.SqlClient/Sistrategia.Data.SqlClient.csproj" />
    <ProjectReference Include="../../src/Data/Sistrategia.Overmind.Data.SqlClient/Sistrategia.Overmind.Data.SqlClient.csproj" />
  </ItemGroup>
</Project>
