/*************************************************************************************************************
* create_security_user_schema.sql is part of the Sistrategia.Security Framework developed by Sistrategia
* Copyright (c) Sistrategia. All rights reserved.
* Licensed under the Apache License, Version 2.0. See LICENSE.txt in the project root for license information.
* 
* Contributor(s):   J. Ernesto Ocampo Cicero, ernesto@sistrategia.com
* Last Update:      2022-Jan-04
* Created:          2010-Sep-08
* Version:          6.0.6829.0
*************************************************************************************************************/

-- -----------------------------------------------------------------------------------------------------------
-- Table [security].[user]
-- -----------------------------------------------------------------------------------------------------------
CREATE TABLE [security].[user] (
     [user_id]                      INT                 NOT NULL
--  ,[user_name]                    NVARCHAR(256)       NOT NULL
    ,[login_name]                   NVARCHAR(256)       NOT NULL
--  ,[full_name]                    NVARCHAR(256)       NOT NULL

    ,[password_hash]                NVARCHAR(256)           NULL
--  ,[password_legacy]              NVARCHAR(128)       NOT NULL
--  ,[password_format]              INT                 NOT NULL CONSTRAINT [def_security_user_password_format] DEFAULT ((0)) -- Password format (0=Plaintext, 1=Hashed, 2=Encrypted)
-- -- ,[password_format]            NVARCHAR(50)        NOT NULL	DEFAULT (('Hashed')) 
    ,[password_salt]                NVARCHAR(128)           NULL

    ,[security_stamp]               NVARCHAR(128)           NULL
    ,[concurrency_stamp]            NVARCHAR(128)           NULL

    ,[email]                        NVARCHAR(256)           NULL
    ,[email_confirmed]              BIT                 NOT NULL DEFAULT((0))

    ,[phone_number]                 NVARCHAR(16)            NULL
    ,[phone_number_confirmed]       BIT                 NOT NULL DEFAULT((0))

    ,[two_factor_enabled]           BIT                 NOT NULL DEFAULT((0))
-- -- ,[lockout_end_date_utc]       DATETIME                NULL
    ,[lockout_end]                  DATETIMEOFFSET          NULL
    ,[lockout_enabled]              BIT                 NOT NULL  DEFAULT((0))
    ,[access_failed_count]          INT                 NOT NULL  DEFAULT((0))
    ,[last_login_at]                DATETIME2               NULL

    ,CONSTRAINT [px_security_user] PRIMARY KEY CLUSTERED ( [user_id] ASC )	
--  ,CONSTRAINT [uqc_security_user_public_key] UNIQUE NONCLUSTERED ( [public_key] ASC )
--  ,CONSTRAINT [uqc_security_user_login_name] UNIQUE NONCLUSTERED ( [login_name] ASC )	
----  ,CONSTRAINT [uqc_security_user_dbrow_identity] UNIQUE CLUSTERED ( [dbrow_identity] ASC )
) 

INSERT INTO [entities].[entity_type] ([entity_type_id],[code_name],[database_schema],[database_table],[database_view]) 
VALUES (4, 'user', 'security', 'user', 'user_view');

-- IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'entities' AND TABLE_NAME = 'event_type'))
-- BEGIN
-- --  INSERT INTO [entities].[event_type] ([code_name],[display_name],[description]) VALUES ('security.organization.new', 'Security.Role.New', 'Event generated by adding a security organization to the system.');
-- --  INSERT INTO [entities].[event_type] ([code_name],[display_name],[description]) VALUES ('security.application.new', 'Security.Application.New', 'Event generated by adding a security application to the system.');
--     INSERT INTO [entities].[event_type] ([code_name],[display_name],[description]) VALUES ('security.role.new', 'Security.Role.New', 'Event generated by adding a security role in the system.');
--     INSERT INTO [entities].[event_type] ([code_name],[display_name],[description]) VALUES ('security.user.new', 'Security.User.New', 'Event generated when adding a user to the system.');
-- END

 --CREATE NONCLUSTERED INDEX [ix_security_user_full_name] ON [security].[user] ([user_id] ASC)
 --INCLUDE ([public_key], [login_name], [full_name], [email], [thumbnail_url])

--CREATE TABLE [AspNetUsers] (
--    [Id] nvarchar(450) NOT NULL,
--    [UserName] nvarchar(256) NULL,
--    [NormalizedUserName] nvarchar(256) NULL,
--    [Email] nvarchar(256) NULL,
--    [NormalizedEmail] nvarchar(256) NULL,
--    [EmailConfirmed] bit NOT NULL,
--    [PasswordHash] nvarchar(max) NULL,
--    [SecurityStamp] nvarchar(max) NULL,
--    [ConcurrencyStamp] nvarchar(max) NULL,
--    [PhoneNumber] nvarchar(max) NULL,
--    [PhoneNumberConfirmed] bit NOT NULL,
--    [TwoFactorEnabled] bit NOT NULL,
--    [LockoutEnd] datetimeoffset NULL,
--    [LockoutEnabled] bit NOT NULL,
--    [AccessFailedCount] int NOT NULL,
--    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY ([Id])
--);

--CREATE TABLE [AspNetUserClaims] (
--    [Id] int NOT NULL IDENTITY,
--    [UserId] nvarchar(450) NOT NULL,
--    [ClaimType] nvarchar(max) NULL,
--    [ClaimValue] nvarchar(max) NULL,
--    CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY ([Id]),
--    CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
--);


--CREATE TABLE [AspNetUserLogins] (
--    [LoginProvider] nvarchar(450) NOT NULL,
--    [ProviderKey] nvarchar(450) NOT NULL,
--    [ProviderDisplayName] nvarchar(max) NULL,
--    [UserId] nvarchar(450) NOT NULL,
--    CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY ([LoginProvider], [ProviderKey]),
--    CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
--);

--CREATE TABLE [AspNetUserTokens] (
--    [UserId] nvarchar(450) NOT NULL,
--    [LoginProvider] nvarchar(450) NOT NULL,
--    [Name] nvarchar(450) NOT NULL,
--    [Value] nvarchar(max) NULL,
--    CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY ([UserId], [LoginProvider], [Name]),
--    CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
--);
--GO

--CREATE INDEX [IX_AspNetRoleClaims_RoleId] ON [AspNetRoleClaims] ([RoleId]);
--GO

--CREATE UNIQUE INDEX [RoleNameIndex] ON [AspNetRoles] ([NormalizedName]) WHERE [NormalizedName] IS NOT NULL;
--GO

--CREATE INDEX [IX_AspNetUserClaims_UserId] ON [AspNetUserClaims] ([UserId]);
--GO

--CREATE INDEX [IX_AspNetUserLogins_UserId] ON [AspNetUserLogins] ([UserId]);
--GO

--CREATE INDEX [IX_AspNetUserRoles_RoleId] ON [AspNetUserRoles] ([RoleId]);
--GO

--CREATE INDEX [EmailIndex] ON [AspNetUsers] ([NormalizedEmail]);
--GO

--CREATE UNIQUE INDEX [UserNameIndex] ON [AspNetUsers] ([NormalizedUserName]) WHERE [NormalizedUserName] IS NOT NULL;
--GO